package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaveRecorder<M extends BaseWaveRecorder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setDeviceName(java.lang.String deviceName) {
		set("device_name", deviceName);
	}
	
	public java.lang.String getDeviceName() {
		return getStr("device_name");
	}
	
	public void setSubstation(java.lang.String substation) {
		set("substation", substation);
	}
	
	public java.lang.String getSubstation() {
		return getStr("substation");
	}
	
	public void setULevel(java.lang.String uLevel) {
		set("u_level", uLevel);
	}
	
	public java.lang.String getULevel() {
		return getStr("u_level");
	}
	
	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}
	
	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}
	
	public void setEdition(java.lang.String edition) {
		set("edition", edition);
	}
	
	public java.lang.String getEdition() {
		return getStr("edition");
	}
	
	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}
	
}

