package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("fault_recorder", "id", FaultRecorder.class);
		arp.addMapping("main_station", "id", MainStation.class);
		arp.addMapping("substation", "id", Substation.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("wave_recorder", "id", WaveRecorder.class);
	}
}


