package com.demo.common.model;

import com.demo.common.model.base.BaseFaultRecorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FaultRecorder extends BaseFaultRecorder<FaultRecorder> {
	
}

