package com.demo.common.model;

import com.demo.common.model.base.BaseMainStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MainStation extends BaseMainStation<MainStation> {
	
}

