package com.demo.common.model;

import com.demo.common.model.base.BaseSubstation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Substation extends BaseSubstation<Substation> {
	
}

