package com.demo.common.model;

import com.demo.common.model.base.BaseWaveRecorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaveRecorder extends BaseWaveRecorder<WaveRecorder> {
	
}

